### ISSUE TITLE
We should maintain the order of layers in the project view

### ISSUE THREAD

**Issue by prashtx** [LocalData/localdata-dashboard#454]
If the user deselects (hides) and reselects (shows) a layer in the embedded project view, that layer is rendered as the topmost layer. We should maintain ordering of layers, so we can avoid awkward visual artifacts and inconsistent presentation.

**Comment by hampelm** [comment]
We can manage this with Leaflet's zindex property: http://leafletjs.com/reference.html#tilelayer-zindex

We can set it manually or base it on the array index when looping over layers
